export interface PossibleTypesResultData {
  possibleTypes: {
    [key: string]: string[];
  };
}
const result: PossibleTypesResultData = {
  possibleTypes: {
    SendTokenResult: ["SendTokenSuccess", "NotFound"],
    SignUpResult: [
      "SignUpSuccess",
      "EmailInvalid",
      "EmailTaken",
      "FirstNameInvalid",
      "LastNameInvalid",
      "CountryInvalid",
    ],
    SignInResult: ["SignInSuccess", "TokenInvalid", "EmailInvalid"],
    RefreshTokenResult: ["RefreshTokenSuccess", "TokenInvalid"],
    SignOutResult: ["SignOutSuccess", "AccessTokenInvalid"],
    GenerateLoginTokenResult: ["GenerateLoginTokenSuccess"],
    GenerateShareTokenResult: ["GenerateShareTokenSuccess"],
    RemoveAccountResult: ["RemoveAccountSuccess", "TokenInvalid"],
    RenameControllerResult: [
      "RenameControllerSuccess",
      "NameInvalid",
      "NotFound",
    ],
    ChangeSetpointResult: [
      "ChangeSetpointSuccess",
      "AwayModeActive",
      "VacationModeActive",
      "NotFound",
    ],
    ChangeModeResult: ["ChangeModeSuccess", "NotFound"],
    ChangeAwayResult: ["ChangeAwaySuccess", "NotFound"],
    ChangeAwaySetpointsResult: ["ChangeAwaySetpointsSuccess", "NotFound"],
    ChangeFanModeResult: ["ChangeFanModeSuccess", "NotFound", "NotSupported"],
    CancelTemperatureHoldResult: ["CancelTemperatureHoldSuccess", "NotFound"],
    CancelFanHoldResult: ["CancelFanHoldSuccess", "NotFound"],
    ChangeScheduleResult: ["ChangeScheduleSuccess", "InactiveSlot", "NotFound"],
    CopyScheduleResult: ["CopyScheduleSuccess", "NotFound"],
    AddLeaveArriveResult: ["AddLeaveArriveSuccess", "NotFound"],
    RemoveLeaveArriveResult: ["RemoveLeaveArriveSuccess", "NotFound"],
    RestoreDefaultScheduleResult: ["RestoreDefaultScheduleSuccess", "NotFound"],
    ChangeHumidificationModeResult: [
      "ChangeHumidificationModeSuccess",
      "NotSupported",
      "NotFound",
    ],
    ChangeHumidificationResult: [
      "ChangeHumidificationSuccess",
      "NotSupported",
      "NotFound",
    ],
    ChangeScheduleOverrideResult: ["ChangeScheduleOverrideSuccess", "NotFound"],
    ChangeAirflowResult: ["ChangeAirflowSuccess", "NotSupported", "NotFound"],
    ToggleAirflowTestResult: [
      "ToggleAirflowTestSuccess",
      "NotFound",
      "NotSupported",
      "Offline",
    ],
    SetAppActiveResult: ["SetAppActiveSuccess", "NotFound"],
    Error: [
      "EmailInvalid",
      "EmailTaken",
      "FirstNameInvalid",
      "LastNameInvalid",
      "CountryInvalid",
      "TokenInvalid",
      "AccessTokenInvalid",
      "NameInvalid",
      "AwayModeActive",
      "VacationModeActive",
      "InactiveSlot",
      "NotFound",
      "NotSupported",
      "Offline",
      "LocationNameInvalid",
      "VacationNotSupported",
      "InvalidEmail",
      "InvalidDate",
      "InvalidCode",
    ],
    RenameLocationResult: [
      "RenameLocationSuccess",
      "LocationNameInvalid",
      "NotFound",
    ],
    ChangeFanCfmResult: ["ChangeFanCfmSuccess", "NotFound", "NotSupported"],
    ChangeLocationAwayResult: ["ChangeLocationAwaySuccess", "NotFound"],
    RegisterLocationResult: ["RegisterLocationSuccess", "NotFound"],
    ChangeDealerResult: ["ChangeDealerSuccess", "NotFound"],
    ChangeProgrammableResult: ["ChangeProgrammableSuccess", "NotFound"],
    ChangeVacationResult: [
      "ChangeVacationSuccess",
      "VacationNotSupported",
      "NotFound",
    ],
    ChangeVacationSetpointsResult: [
      "ChangeVacationSetpointsSuccess",
      "VacationNotSupported",
      "NotFound",
    ],
    RefreshStatusResult: ["RefreshStatusSuccess", "NotFound", "Offline"],
    RemoveLocationResult: ["RemoveLocationSuccess", "NotFound"],
    ResetLogsResult: ["ResetLogsSuccess", "NotFound", "NotSupported"],
    Notification: [
      "FaultNotification",
      "FilterNotification",
      "HumidityNotification",
      "OfflineNotification",
      "ServiceReminder",
      "TemperatureNotification",
    ],
    SubscribeToNotificationsResult: ["SubscribeToNotificationsSuccess"],
    UnsubscribeFromNotificationsResult: [
      "UnsubscribeFromNotificationsSuccess",
      "NotFound",
    ],
    ToggleFaultNotificationResult: [
      "ToggleFaultNotificationSuccess",
      "NotFound",
    ],
    ToggleHumidityNotificationResult: [
      "ToggleHumidityNotificationSuccess",
      "NotFound",
    ],
    AdjustHumidityNotificationThresholdResult: [
      "AdjustHumidityNotificationThresholdSuccess",
      "NotFound",
    ],
    ToggleServiceReminderResult: ["ToggleServiceReminderSuccess", "NotFound"],
    AdjustServiceReminderDatesResult: [
      "AdjustServiceReminderDatesSuccess",
      "NotFound",
    ],
    ToggleTemperatureNotificationResult: [
      "ToggleTemperatureNotificationSuccess",
      "NotFound",
    ],
    AdjustTemperatureNotificationThresholdResult: [
      "AdjustTemperatureNotificationThresholdSuccess",
      "NotFound",
    ],
    ShareLocationResult: [
      "ShareLocationSuccess",
      "InvalidDate",
      "InvalidEmail",
      "NotFound",
    ],
    RevokeShareResult: ["RevokeShareSuccess", "NotFound"],
    RequestShareResult: ["RequestShareSuccess", "InvalidEmail"],
    ChangeTemperatureUnitResult: ["ChangeTemperatureUnitSuccess"],
    ConvertToHomeownerAccountResult: ["ConvertToHomeownerAccountSuccess"],
    ConvertToProAccountResult: ["ConvertToProAccountSuccess", "InvalidCode"],
  },
};
export default result;
